# Header
menu:
  首页: /
  目录: /archives/
  关于: /about/

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://cdn.baotingart.com/baotingart/static/cover-detail.jpg"

# webmaster
baidu_site_verification: DfXkdwNU9J
google_site_verification: LzN7u6ht_04hkiV6sqRef71w7tiLMtBkqiB9nKuBZRw
favicon: http://cdn.baotingart.com/baotingart/static/favicon.ico
appicon: http://cdn.baotingart.com/baotingart/static/appicon-192x192.png
baidu_tongji: 3335afbcaebac61ab8c10f377a0928b5

# comments
comments: true

# Social Accounts
weixin_url:
weibo_url: http://weibo.com/imbaobaojia
linkedin_url: http://www.linkedin.com/in/%E5%A9%B7-%E5%8C%85-81a5ba139/
rss_url: /rss2.xml
