# Header
menu:
  首页: /
  目录: /archives/
  关于: /about/

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://fatcamera.b0.upaiyun.com/baotingart/static/cover-detail.jpg"

# Social Accounts
weixin_url:
weibo_url: http://weibo.com/imbaobaojia
linkedin_url: https://www.linkedin.com/in/%E5%A9%B7-%E5%8C%85-81a5ba139/
rss_url: /rss2.xml
